site_name: "Isocomp"
site_description: "Extend the utility of long-read RNAseq for investigating Mendelian diseases between multiple samples."
site_author: "Yutong Qiu, Chia Sin Liew, Rupesh Kesharwani, Bida Gu, Chase Mateusiak, Muhammad Sohail Raza, Evan Biederstedt"
site_url: "https://github.com/collaborativebioinformatics/isocomp"
repo_url: "https://github.com/collaborativebioinformatics/isocomp"
repo_name: "isocomp"
edit_uri: "edit/master/docs/"
watch: ['src/isocomp']

theme:
  name: readthedocs

plugins:
- search
- autorefs
- section-index
- mkdocs-jupyter
- mkdocstrings:
    handlers:
          python:
            paths: [src/isocomp]  # search packages in the src folder
            docstring_style: 'google'
            merge_init_into_class: True

nav:
- Install:
  - install.md
- "Algorithm Overview":
  - algorithm_overview/algorithm_description.md
- "Command Line Usage": 
  - cmd_line/cmd_line_usage.md
- "API and API usage":
  - Modules:
    - Coordinates: 
      - Classes:
        - Window: api/coordinates/classes/Window.md
      - Functions:
        - create_comparison_windows: api/coordinates/functions/create_comparison_windows.md
    - Compare:
      - Classes:
        - IsoformLibrary: api/compare/classes/IsoformLibrary.md
      - Functions:
        - align_isoforms: api/compare/functions/align_isoforms.md
        - vector_crosser: api/compare/functions/vector_crosser.md
        - compare_isoforms_in_cluster: api/compare/functions/compare_isoforms_in_cluster.md
        - filter_comparisons: api/compare/functions/filter_comparisons.md
        - find_unique_isoforms: api/compare/functions/find_unique_isoforms.md

  - "Using the API": api/api_tutorial.ipynb
- "Summaries of Similar Softwares":
  - "Cupcake/Tofu FusionFinder": other_software_summaries/tofu_fusion_genes.md

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists